spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    topic-name: order_topics
    create-order-topic:
      name: create_order_topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer

  datasource:
    url: ${SPRING_DATASOURCE-URL:jdbc:mysql://localhost:3306/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_USERNAME:Nnn@2002}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 60000

  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
server:
    port: 9089